# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e1e431767cfcfe7af9c9cc797d02122521a4458a9cf4bbd59718dde0196490284f923cacfe5756a5dee69ab2b2699167bbd05f15f2f9ffd6fd650ec507d0ca0

test:
  secret_key_base: c1bb64df5fff2a4f5b0597480e03db060634024284e71bf1ad3c492b14caf4090002fbc99a6f9548776dd67d541a5f686c76d661fd80fca9ab1c1d1feb7d47a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
